USE [Task3]
GO

/****** Object:  Table [dbo].[Dates]    Script Date: 4/6/2025 1:52:46 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Dates](
	[Id] [bigint] NOT NULL,
	[Dt] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC,
	[Dt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


